### ISSUE TITLE
The "Diagnostic next" and "Diagnostic previous" mappings disappeared in v4

### ISSUE THREAD

**Issue by acarl005** [AstroNvim/astrolsp#11]
### Checklist

- [X] I have searched through the AstroNvim docs
- [X] I have searched through the existing issues of AstroNvim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

NVIM v0.10.0-dev-2128+g78b000c74-Homebrew

### Operating system/version

MacOS 14.4.1 (23E224)

### Terminal/GUI

Warp terminal

### Describe the bug

In the [LSP mappings](https://docs.astronvim.com/mappings/#lsp-mappings), there are "diagnostic next" and "diagnostic previous" mapped to `]d` and `[d` by default. However, they do not exist in my setup. I looked in which-key, and in telescope using `<leader>fk`. No sign of them.

### Steps to Reproduce

Try `[d` or `]d` in a file with LSP set up and having some diagnostic errors.

### Expected behavior

The `[d` and `]d` bindings should be defined by default as they appear in the docs.

### Additional Context

These worked in astronvim v3 and I use them heavily.

**Comment by mehalter** [comment]
Your neovim nightly is out of date. Also neovim nightly is not officially supported. Be sure to make sure you are keeping up with the development if you want to take the responsibility of trying to use nightly. Also the current AstroNvim v4 release requires neovim master until tomorrow's nightly

**Comment by acarl005** [comment]
Ah silly me. I tried on Neovim stable and the keybinding is there as expected. Thanks for calling that out. I'll stick to stable for now.
