### ISSUE TITLE
Error when processing autocommnd "*" of LSPProgress

### ISSUE THREAD

**Issue by Asthestarsfalll** [AstroNvim/astrolsp#12]
### Checklist

- [X] I have searched through the AstroNvim docs
- [X] I have searched through the existing issues of AstroNvim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

NVIM v0.10.0-dev-3097+g064f3e42e8

### Operating system/version

manjaro 5.5.13

### Terminal/GUI

kitty

### Describe the bug

```
Error executing lua callback: ...zh/.local/share/nvim/lazy/astrolsp/lua/astrolsp/init.lua:38: attempt to index field 'result' (a nil value)
stack traceback:
	...zh/.local/share/nvim/lazy/astrolsp/lua/astrolsp/init.lua:38: in function 'progress'
	...zh/.local/share/nvim/lazy/astrolsp/lua/astrolsp/init.lua:251: in function <...zh/.local/share/nvim/lazy/astrolsp/lua/astrolsp/init.lua:251>
	[C]: in function 'nvim_exec_autocmds'
	/usr/share/nvim/runtime/lua/vim/lsp/handlers.lua:53: in function 'handler'
	...ocal/share/nvim/lazy/null-ls.nvim/lua/null-ls/client.lua:233: in function <...ocal/share/nvim/lazy/null-ls.nvim/lua/null-ls/client.lua:232>
Error executing lua callback: ...al/share/nvim/lazy/noice.nvim/lua/noice/lsp/progress.lua:20: attempt to index local 'result' (a nil value)
stack traceback:
	...al/share/nvim/lazy/noice.nvim/lua/noice/lsp/progress.lua:20: in function 'progress'
	...al/share/nvim/lazy/noice.nvim/lua/noice/lsp/progress.lua:95: in function <...al/share/nvim/lazy/noice.nvim/lua/noice/lsp/progress.lua:94>
	[C]: in function 'nvim_exec_autocmds'
	/usr/share/nvim/runtime/lua/vim/lsp/handlers.lua:53: in function 'handler'
	...ocal/share/nvim/lazy/null-ls.nvim/lua/null-ls/client.lua:233: in function <...ocal/share/nvim/lazy/null-ls.nvim/lua/null-ls/client.lua:232
```

### Steps to Reproduce

Maybe update to nvim 0.10.0 will reproduce this.

### Expected behavior

Just no error

### Screenshots

![240509_14h55m32s_screenshot](https://github.com/AstroNvim/astrolsp/assets/72954905/7c3b2bd3-1b45-4cee-91de-c62275689c9a)

**Comment by mehalter** [comment]
Your neovim nightly is out of date

**Comment by l1nxy** [comment]
Same here, the newest nightly version neovim also report this error. the stable version will not.

**Comment by Asthestarsfalll** [comment]
I update to latest neovim  and update AstroNvim and all piugins. This error still remain.

**Comment by mehalter** [comment]
This is because you don't have the latest commits of AstroLSP. You are using stable AstroNvim with the stable released plugins. If you are attempting to use Neovim nigthly (which is not supported) then you probably want to also use unstable/nightly AstroNvim because released versions of plugins may not support neovim nightly

**Comment by Reledia** [comment]
I have the same errors, with `NVIM v0.10.0-dev-3070+gcf9f002f3`, Astrocommunity at commit c897864, AstroLSP at b967bde, Astrocore at 37bbe5d and AstroNvim version 4.6.7 at ad3fe27. 
This happens only when opening a Lua file

**Comment by mehalter** [comment]
@Reledia I promise this isn't a bug in AstroNvim or AstroLSP. If you cannot get it working or debug your configuration I would recommend using neovim stable

**Comment by mehalter** [comment]
@Reledia I just checked the commit you are on and it is an hour extremely out of date neovim nightly release from last week so it is very much expected that you would get this error since your editor is out of date: https://github.com/neovim/neovim/commit/cf9f002f31c8b4d9d42912a3f45f5d3db4462fd9

You should make sure if you are attempting to use neovim nightly that you are keeping up with the changes and understanding that not every plugin will support the most recent nightly release and some may require the most recent nightly release.

**Comment by Reledia** [comment]
@mehalter Of course I understand that. I am using the latest version on the chaotic-aur, and I only wanted to check if others were having the same problem and if it was due to astrolsp. Sorry for taking your time

**Comment by mehalter** [comment]
No problem! Yeah it's because that package is very out of date in terms of nightly releases and we are updated to handle more recent neovim development on neovim

**Comment by Reledia** [comment]
For what is worth, I can confirm using the latest nightly release from github resolved all problems :+1: Thanks again
