### ISSUE TITLE
Run config failing 

### ISSUE THREAD

**Issue by benmaia** [AstroNvim/astrolsp#14]
### Checklist

- [X] I have searched through the AstroNvim documentation
- [X] I have searched through the existing issues of this project
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

0.10.0

### Operating system/version

ubuntu 20.04

### Terminal/GUI

windows terminal

### Describe the bug

As soon as I open neovim, this notification appears

### Steps to Reproduce

Git clone the repo, remove the .git directory, open nvim.

### Expected behavior

It gives me an error on lsp config

### Screenshots

![Screenshot 2024-07-08 163532](https://github.com/AstroNvim/astrolsp/assets/86362288/1f0d58b9-04e2-4de3-8855-06aa33b2d015)

**Comment by mehalter** [comment]
Looks like you have an out of date version of Neovim. You are probably using some neovim 0.10 nightly before the official release that has the old `vim.lsp.inlay_hint.enable` API that changed before the release.

**Comment by mehalter** [comment]
Relevant commit that you are missing: https://github.com/neovim/neovim/commit/f1dfe32bf5552197e0068298b0527526a4f918b1

Please only use stable neovim as that's the only thing AstroNvim supports

**Comment by mehalter** [comment]
Also when filling out the issue form please run the actual `nvim -v` command and paste the output for your version. That's there to identify errors like this
