### ISSUE TITLE
Unable to map insert-mode <C-s> 

### ISSUE THREAD

**Issue by IIamaseconds** [AstroNvim/astrolsp#9]
### Checklist

- [X] I have searched through the AstroNvim docs
- [X] I have searched through the existing issues of AstroNvim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

0.9

### Operating system/version

macOS

### Terminal/GUI

warp

### Describe the bug

I use CTRL-s for saving while in insert-mode. 
This is not possible using AstroLSP since it seems to reserve the shortcut for itself and cannot be overriden.

I am not completely sure how it works, and the only time the key works is when AstroLSP is removed from the plugin list. 

### Steps to Reproduce

- Use the AstroNvim template, add mapping.lua with insert-mode for <C-s> bound to a command. This does not work.
- Remove AstroLSP as a plugin and restart. Now the shortcut works

### Expected behavior

Command executes when combination is pressed in insert-mode.

**Comment by mehalter** [comment]
This is a new default in neovim 0.10 that we have backported to AstroNvim. We normalize our mappings to the official keycodes in the vim documentation.

The casing of the key here should be `<C-S>`. Here is a correct example for you to remove this mapping:

```lua
return {
  "AstroNvim/astrolsp",
  opts = {
    mappings = {
      i = {
        ["<C-S>"] = false
      }
    }
  }
}
```

**Comment by mehalter** [comment]
Also us backporting this mapping actually does break our own default mapping of `<C-S>` being mapped to save. I have reverted this and will release soon. So the above code will be unnecessary and your own mapping of `<C-S>` for save is also unnecessary since it's a default
